name: Workflow 2
on: issues
jobs:
    issue:
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v5
            -   name: Install Nodejs
                uses: actions/setup-node@v6
                with:
                    node-version: 18
            -   name: Install Dependencies
                run: npm ci
            -   name: Printing Context
                run: echo "${{toJson(github.event)}}"