name: Workflow 1
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v5
            -   name: Install Nodejs
                uses: actions/setup-node@v6
                with:
                    node-version: 18
            -   name: Install Dependencies
                run: npm ci
            -   name: Run tests
                run: npm test
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v5
            -   name: Install Nodejs
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Install Dependencies
                run: npm ci
            -   name: Run Lint
                run: npm run lint  
    Deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v5
            -   name: Install Nodejs
                uses: actions/setup-node@v6
                with:
                    node-version: 18
            -   name: Install Dependencies
                run: npm ci
            -   name: Build Application
                run: npm build
            -   name: Deploy
                run: echo "Deploying..."
